### ISSUE TITLE
flow-compatible abstraction over tcomb

### ISSUE THREAD

**Issue by zerkalica** [gcanti/babel-plugin-tcomb#11] opened 2016-03-23 08:58 UTC
Can you explain in readme, why you abandon idea of unobtrusive flow-based type-checking? (https://github.com/gcanti/flowcheck)

babel-plugin-tcomb doesn't support flow type annotations. It support you own standard of type declarations, based on tcomb. It's so difficult to create gracefully degraded to flow abstraction over tcomb?

**Comment by gcanti** [comment] 2016-03-24 07:34
Hi @zerkalica,

Since my data structures and domain models are already implemented with `tcomb` I just needed a quick way to type-check functions using `tcomb` types without using `t.func` combinator (which I find kind of annoying).

> It's so difficult to create gracefully degraded to flow abstraction over tcomb?

Not sure what you mean, Could you elaborate a little bit? What's your use case?

**Comment by zerkalica** [comment] 2016-03-24 10:36
I mean, how to combine static type checking with runtime checking without boilerplate code:

```js
/* @flow */
import {
    String as string,
    struct
} from 'tcomb'

const MyObj = struct({
    t: string
})
type MyObj = {
    t: string;
}
export function test(arg: MyObj): MyObj {
    return arg
}

test({
    t: 123 // flow generates error
})
```

Just transpile
```js
type MyObj = {
    t: string;
}
```

into

```js
const MyObj = struct({
    t: string
})
```

**Comment by gcanti** [comment] 2016-06-01 16:24
Hi @zerkalica,

working on this (again...hope I have some good news though).

I'm compiling:

- `string` to `t.String`
- `number` to `t.Number`
- `boolean`, `bool`to `t.Boolean`
- `any`, `mixed` to `t.Any`
- `void`, `null` to `t.Nil`

It's not required to do the trick you suggested:

```js
import {
    String as string // trick
} from 'tcomb'
```

Example

```js
import t from 'tcomb';

function foo(x: string) {
  return x
}
```

now compiles to: 

```js
import t from 'tcomb';

function foo(x: string) {
  t.assert(t.is(x, t.String), 'Invalid argument x (expected a ' + t.getTypeName(t.String) + ')');

  return x;
}
```

Note the new `t.is` call, here's its code in `tcomb`: 

```js
var isType = require('./isType');

// returns true if x is an instance of type
module.exports = function is(x, type) {
  if (isType(type)) {
    return type.is(x);
  }
  return x instanceof type; // type should be a class constructor
};
```

The `x instanceof type` part will allow to handle non-tcomb types, generics included:

```js
import t from 'tcomb';

function foo(p: Promise<string>): void {}

foo(1) // throws [tcomb] Invalid argument p (expected a Promise)
```

at the same time Flow throws:

index.js:9
  9: foo(1)
         ^ number. This type is incompatible with
  5: function foo(p: Promise<string>): void {
                     ^^^^^^^^^^^^^^^ Promise


Now, coming to your last example, this works:

```js
import t from 'tcomb'

const MyObj = t.interface({
    t: t.String
}, 'MyObj')

export function test(arg: MyObj): MyObj {
    return arg
}

test({
    t: 123 // throws [tcomb] Invalid argument arg (expected a MyObj)...
})
// ...while Flow says no errors!
```

but this doesn't:

```js
/* @flow */
type MyObj = {
  t: string
};

export function test(arg: MyObj): MyObj {
    return arg
}

test({
    t: 123 // here Flow correctly throws "number. This type is incompatible with string"
})
```

because JavaScript throws "ReferenceError: MyObj is not defined".

Now we could check that `MyObj` is defined, i.e. something like:

```js
function test(arg: MyObj): MyObj {
  MyObj = typeof MyObj !== 'undefined' ? MyObj : t.Any; 
  t.assert(t.is(arg, MyObj), 'Invalid argument arg (expected a ' + t.getTypeName(MyObj) + ')');

  ...
}
```

or we could compile:

```js
type MyObj = {
  t: string
};
```

to:

```js
const MyObj = t.interface({
  t: t.String
})
```

Not sure what's better, what do you think?

/cc @ctrlplusb @Chrisui @ivan-kleshnin @majhork

**Comment by ctrlplusb** [comment] 2016-06-01 18:00
This is pretty epic @gcanti.  Fantastic as always.

My vote is for the transpilation of `type MyObj` to `const MyObjet = t.interface`.  Certainly more work but I feel like it would be a fantastic move for `tcomb` if you can support as much of the flow syntax as possible.  Firstly, it could lead to greater `tcomb` adoption, granting a migration path for existing `flow` users.  Additionally this library is already piggy backing off the babel flow syntax plugin, so I believe it will make things feel much more natural if we move to support the "native" flow syntax - which could save us a headache or two in the future, or provide us with a great base from which to adapt against flow syntax changes/extensions.

**Comment by gcanti** [comment] 2016-06-01 22:08
Ok we got type aliases

```js
type Person = {
  name: string,
  surname?: string,
  age: number,
  tags: Array<string>
};

function getFullName(p: Person) {
  return `${p.name} ${p.surname}`
}

getFullName({})
```

**tcomb** (at runtime)

```js
throws [tcomb] Invalid argument p (expected a Person)
```

<img width="609" alt="tcomb" src="https://cloud.githubusercontent.com/assets/878912/15727329/04f1ce52-2856-11e6-99b4-01d7079cdadf.png">


**Flow**

```sh
> flow
index.js:14
 14: getFullName({})
     ^^^^^^^^^^^^^^^ function call
 10: function getFullName(p: Person) {
                             ^^^^^^ property `age`. Property not found in
 14: getFullName({})
                 ^^ object literal

index.js:14
 14: getFullName({})
     ^^^^^^^^^^^^^^^ function call
 10: function getFullName(p: Person) {
                             ^^^^^^ property `name`. Property not found in
 14: getFullName({})
                 ^^ object literal

index.js:14
 14: getFullName({})
     ^^^^^^^^^^^^^^^ function call
 10: function getFullName(p: Person) {
                             ^^^^^^ property `tags`. Property not found in
 14: getFullName({})
                 ^^ object literal


Found 3 errors
```

The problem now is: I don't know how to define refinements without irritate Flow:

```js
/* @flow */

import t from 'tcomb'

type Person = {
  name: string,
  surname?: string,
  age: number,
  tags: Array<string>
};

const PersonRefinement = t.refinement(Person, p => p.surname === 'aaa')
```

```sh
> flow
index.js:12
 12: const PersonRefinement = t.refinement(Person, p => p.surname === 'aaa')
                                      ^^^^^^ Person. type referenced from value position
  5: type Person = {
          ^^^^^^ type Person


Found 1 error
```

**Comment by zerkalica** [comment] 2016-06-01 22:10
First of all create normal reflection layer for each type, constructor, method and function.

There are many realisations: [babel-plugin-type-metadata](https://github.com/stephanos/babel-plugin-type-metadata), [babel-plugin-angular2-annotations](https://github.com/shuhei/babel-plugin-angular2-annotations), or my [babel-plugin-transform-metadata](https://github.com/zerkalica/babel-plugin-transform-metadata)

```js
// interfaces.js
// @flow

export type User = {
  name: string;
}
```
to:

```js
// interfaces.js
// @flow
import t from 'tcomb'
export type User = {
  name: string;
}

export tcomb$User = t.interface({
  name: t.string
})
```

Interface usage:

```js
// @flow
import type {User} from './interfaces'

function test(user: User): void {}
```

to

```js
// @flow
import type {User} from './interfaces'
import {tcomb$User} from './interfaces'
import t from 'tcomb'

const metadata$test = [tcomb$User]
function test(user: User): void {
  t.assert(metadata$test)
}
Reflect.defineMetadata('design:paramtypes', metadata$test, test)
```

PS:
I think, it's too hard to create real flow-compatible runtime checking. Look at https://github.com/codemix/babel-plugin-typecheck, it supports generics, imports/exports, optimizations. Code base about 3000 lines, but stil not flow-compatible.

**Comment by gcanti** [comment] 2016-06-02 07:53
> it's too hard to create real flow-compatible runtime checking

Yes I agree, but my goal is different, for instance I don't want to re-implement at runtime what can be done only by Flow, I think it's not even possible. 

Static type checking and runtime type checking are complementary:

- static type checking: typos, generics, refactoring, cross file type errors (i.e. you change a LOC in a file and you break the code of another part of the app)
- runtime type checking: refinements, runtime type introspection, use cases when you can't setup Flow

> First of all create normal reflection layer for each type, constructor, method and function

Not sure I'm following, why you'd do that? The goal is to type-check, not to feed the reflection API (which is still just a proposal at this time)

**Comment by zerkalica** [comment] 2016-06-02 08:28
Reflect polyfil just an example. Main idea - generate and share tcomb metada for different puproses
and access them in runtime.
For example, for form validation: https://github.com/seanhess/runtime-types

**Comment by ivan-kleshnin** [comment] 2016-06-02 09:57
> Main idea - generate and share tcomb metada for different puproses and access them in runtime.

Ending with parallel type definions... Who will track and solve unsyc issues?

**Comment by gabro** [comment] 2016-06-02 13:04
@gcanti just to understand the refinement problem a bit better, even if you disambiguate the usage of a type as a value, how are you going to use the refinement anyway?

Basically, this:

```js
import t from 'tcomb'

type Person = {
  name: string,
  surname?: string,
  age: number,
  tags: Array<string>
};

const PersonRefinement = t.refinement(Person, p => p.surname === 'aaa')
                                                              //   ^___ suppose this works, somehow

function getSurname(p: PersonRefinement) { // how does flow react to this?
  return p.surname;
}
```

**Comment by zerkalica** [comment] 2016-06-02 13:10
@ivan-kleshnin What you mean, what is unsync issues?

**Comment by gcanti** [comment] 2016-06-02 13:56
> how does flow react to this?

@gabro After a few hours of trials I'd say... "badly". You can't use a value as a type annotation (at least I didn't find a way).

There's a divide between the world of types and the world of values so it seems you must choose: either you give up on refinements and RTI:

```js
// @flow

type Person = {
  name: string
};

function foo(p: Person) {
  return p.name
}

foo({}) // flow throws property `name`. Property not found in
        // tcomb throws [tcomb] Invalid argument p (expected a Person)
```

or you give up on static type checking and go dynamic (you gain refinements and RTI):

```js
import t from 'tcomb'

const Person = t.interface({
  name: t.String
})

function foo(p: Person) {
  return p.name
}

foo(Person({})) // tcomb throws Invalid value undefined supplied to {name: String}/name: String
                // no errors for Flow
```

There is a slightly verbose middle ground to explore though (static + dynamic):

```js
// @flow

import t from 'tcomb'

type Person = {
  name: string
};

const PersonRefinement = t.refinement(t.Object, p => p.name.length < 3)

function foo(p: Person) {
  t.assert(PersonRefinement.is(p), 'bad!');
  return p.name
}

foo({ name: 'Giulio' }) // no errors for flow but tcomb throws [tcomb] bad!
```

**Comment by gabro** [comment] 2016-06-02 13:58
Isn't there a way of making a pass before flow does?

I think if we can have some kind of pipeline

```
pre-flow &rarr; flow &rarr; babel-plugin
```

we might do something interesting

**Comment by gcanti** [comment] 2016-06-02 14:12
I'm hesitant to go that route. I don't exclude a pre-processing step but it's potentially cumbersome, the nice thing about Flow is that you throw at it your source file and you are done.

**If** this thing works well, my preference at the moment is going completely static except for some strategic domain models which I may want to define as refinements.

**Comment by gcanti** [comment] 2016-06-02 16:19
Just added support for interfaces:

```js
interface A {
  a: string;
}

interface B extends A {
  b: string;
}
```

to

```js
const A = t.interface({
  a: t.String
}, "A");

const B = t.interface.extend([A, {
  b: t.String
}], "B");
```

**Comment by gcanti** [comment] 2016-06-03 15:17
A "real world" example: type-checking redux (state and actions) https://github.com/gcanti/redux-tcomb/issues/9#issuecomment-223576027

**Comment by gcanti** [comment] 2016-06-05 08:13
Added a `_assert` helper that gives better error messages:

```js
import t from 'tcomb'

const MyObj = t.interface({
  t: t.String
}, 'MyObj')

export function test(arg: MyObj): MyObj {
  return arg
}

// before: [tcomb] Invalid argument arg (expected a MyObj)...
// now: [tcomb] Invalid value 123 supplied to arg: MyObj/t: String
test({
    t: 123
})
```

Source:

```js
import t from 'tcomb'

const MyObj = t.interface({
  t: t.String
}, 'MyObj')

export function test(arg: MyObj): MyObj {
  return arg
}
```

Output:

```js
import t from 'tcomb'

function _assert(x, type, name) {
  ...
}

const MyObj = t.interface({
  t: t.String
}, 'MyObj')

export function test(arg: MyObj): MyObj {
  _assert(arg, MyObj, 'arg');

  var ret = function (arg) {
    return arg;
  }.call(this, arg);

  _assert(ret, MyObj, 'return value');

  return ret;
}
```

**Comment by gcanti** [comment] 2016-06-05 10:41
I have a proposal in order to support refinements, but it's kinda hacky, I'd love to hear what you think:

Let's define a special interface `Refinement`:

```js
interface Refinement<P: (x: any) => boolean> {}
```

`Refinement` is a "placeholder" and won't be compiled by the babel plugin.

**Usage**

```js
interface Refinement<P: (x: any) => boolean> {}

const isPositive = x => x >= 0

// "typeof isInteger" will allow the babel plugin to compile the actual refinement
// picking the "isPositive" identifier while Flow sees only the type: number
type Positive = number & Refinement<typeof isPositive>;

function foo(x: Positive) {}

foo(-1) // ok for Flow (obviously it can't type-check refinements)
foo('a')
/*
index.js:14
 14: foo('a')
     ^^^^^^^^ function call
 14: foo('a')
         ^^^ string. This type is incompatible with
 10: type Positive = number & Refinement<typeof isPositive>;
                     ^^^^^^ number
*/
```

compiles to:

```js
const isPositive = x => x >= 0

// here the babel plugin does its magic
const Positive = t.refinement(t.Number, isPositive, 'Positive');

function foo(x: Positive) {
  _assert(x, Positive, 'x')
  ...
}

// tcomb can type-check refinements
foo(-1) // throws [tcomb] Invalid value -1 supplied to x: Positive
foo('a') // throws [tcomb] Invalid value "a" supplied to x: Positive
```

Same for interfaces:

```js
interface A {
  name: string;
}

const predicate = (x: A) => x.name.length > 3

interface B extends A, Refinement<typeof predicate> {}

function foo(b: B) {}

foo({name: 1})
```

compiles to:

```js
const A = t.interface({
  name: t.String
}, 'A')

const predicate = (x: A) => x.name.length > 3

const B = t.interface.extend([A, t.refinement(t.interface({
}), predicate)], 'B');
```

/cc @giogonzo

**Comment by giogonzo** [comment] 2016-06-05 14:14
what kind of ancient sorcery am I looking at? jk, looks awesome 😀 

> `type Positive = number & Refinement<typeof isPositive>`
> picking the "isPositive" identifier while Flow sees only the type: number

why is this the case?

> `interface B extends A, Refinement<typeof predicate> {}`

same here, what's the `,`?

Apart from some context I'm missing on flow type annotations syntax, yes, this looks kind of hacky / burden on the end user. But yeah! for profit

**Comment by gcanti** [comment] 2016-06-05 15:27
> why is this the case?

AFAIK because `interface` can describe almost anything and Flow doesn't assume it describes objects, so:

```js
interface Refinement<P: (x: any) => boolean> {}
```

is equivalent to `type Refinement<P: (x: any) => boolean> = any;` or simply `any` so

```js
type T1 = number & Refinement<typeof isPositive>;
// which is equivalent to
type T2 = number & any;
// which is equivalent to
type T3 = number
```

> same here, what's the ,?

an interface can extend `n` other interfaces

**Comment by gcanti** [comment] 2016-06-05 17:31
Just pushed a candidate implementation (`refinements` branch). 

Despite being black magic, I'm really tempted because it's working extraordinarily well.

For example, adding the following simple file definition:

```js
declare module 'tcomb' {

  declare interface Refinement<P: (x: any) => boolean> {}

  declare type Integer = number & Refinement;

}
```

I'm now able to do this:

```js
import type { Refinement, Integer } from 'tcomb'

const p = n => n >= 2

type IntegerGreaterThan2 = Integer & Refinement<typeof p>;

function foo(n: IntegerGreaterThan2) {
  return n
}

foo(2) // flow ok, tcomb ok
foo(1) // flow ok, tcomb throws [tcomb] Invalid value 1 supplied to n: IntegerGreaterThan2
foo(2.1) // flow ok, tcomb throws [tcomb] Invalid value 2.1 supplied to n: IntegerGreaterThan2
foo('a') // flow throws, tcomb throws
```

**Comment by gabro** [comment] 2016-06-06 11:14
This is great! I think the opportunities this solution opens greatly outweigh the "hackish feel". Well done! 👍

**Comment by gcanti** [comment] 2016-06-07 09:07
Another proposal, **validating (at runtime) the IO boundary using typecasts**:

```js
type User = { name: string };

export function getUser(userId: string): Promise<User> {
  return axios.get('...').then(p => (p: User))
}
```

to

```js
const User = require('tcomb').interface({
  name: require('tcomb').String
}, 'User');

export function getUser(userId: string): Promise<User> {
  _assert(userId, require('tcomb').String, 'userId');

  const ret = function (userId) {
    return axios.get('').then(p => {
      return _assert(p, User, 'p'); // <= runtime validation
    });
  }.call(this, userId);

  _assert(ret, Promise, 'return value');

  return ret;
}
```

**Comment by gcanti** [comment] 2016-06-09 06:03
Last topic: anyone has an idea about getting runtime type introspection?

```js
type Person = {
  name: string
};

// this is ok in the runtime world
console.log(Person.meta) // => {kind: 'interface', props: ...}
```

but in the static world Flow throws:

```
index.js:9
  9: console.log(Person.meta)
                 ^^^^^^ Person. type referenced from value position
  5: type Person = {
          ^^^^^^ type Person
```

/cc @samwgoldman

**Comment by zerkalica** [comment] 2016-06-09 09:10
```js
// @flow
import {_, getIntrospection} from 'tcomb'

type Person = {name: string}

console.log(getIntrospection((_: Person)))
```
_ is a dummy var with any type.

babel converts (_: Person) to Person.meta

**Comment by gabro** [comment] 2016-06-09 12:00
As discussed offline, if we make an assignment mandatory, this becomes possible

```js
import type reify from 'tcomb';

declare interface Person {
  name: string
}

let Person: reify<Person>;

console.log(Person.meta);
```

**Comment by zerkalica** [comment] 2016-06-09 12:11
Two errors:
Name is already bound and Property cannot be accessed on possibly undefined value

May be try this?

```js
console.log((_: reify<IPerson>).meta);
```

**Comment by gabro** [comment] 2016-06-09 12:23
Slightly different syntax, but essentially the same thing

```jsx
import { reify } from 'tcomb';
import type type from 'tcomb;

declare interface Person {
  name: string
}

let tPerson: type<Person> = reify; /// void

console.log(tPerson.meta);
```

where

```jsx
export type type<T> = any;
export const reify = null;
```

No changes introduced, other than explicitly providing a value (`reify`) to use on the rhs.

**Comment by gcanti** [comment] 2016-06-09 12:53
@gabro it doesn't work with version 0.26.0 :(

This works though (and being an expression seems more versatile):

```js
import type { $Reify } from 'tcomb'

type Person = {
  name: string
};

const X = (({}: any): $Reify<Person>)
X.meta // OK
if (X.meta.kind === 'interface') {
  X.meta.props // OK
}
```

tested against the following incomplete (WIP) definition file:

```js
declare module 'tcomb' {

  // runtime type introspection
  declare type $Reify<T> = Type<T>;

  declare type MetaIrreducible = {
    kind: 'irreducible'
  };

  declare type MetaList = {
    kind: 'list',
    type: Type
  };

  declare type MetaInterface = {
    kind: 'interface',
    props: {[key: string]: Type}
  };

  // TODO(giu) describe all meta objects
  declare type Meta =
      MetaIrreducible
    | { kind: 'refinement' }
    | { kind: 'maybe' }
    | { kind: 'struct' }
    | MetaInterface
    | { kind: 'func' }
    | { kind: 'tuple' }
    | MetaList
    | { kind: 'dict' }
    | { kind: 'enums' }
    | { kind: 'union' }
    | { kind: 'intersection' };

  declare interface $Refinement<P: (x: any) => boolean> {}

  declare interface Type<T> {
    (x: T): T;
    is(x: any): boolean;
    meta: Meta;
  }

  declare class Tcomb {

    // utils
    assert(guard: boolean, message?: string | () => string): void;
    stringify(x: any): string;

    // irreducibles
    Nil: Type<void | null>;
    String: Type<string>;
    Number: Type<number>;
    Boolean: Type<boolean>;
    Integer: Type<number>;
    Function: Type<Function>;
    Array: Type<Array<any>>;

    // combinators
    list<T>(type: Type<T>, name?: string): Type<Array<T>>;

  }

  declare var exports: Tcomb;
}
```

**Comment by gcanti** [comment] 2016-06-09 15:44
Closing this as per cea8fc10e752f7ce2f2d3388629d300d51a3f493.

**Closed by gcanti** 2016-06-09 15:44 UTC
Labels: discussion, Status: Completed

**Comment by gcanti** [comment] 2016-06-09 15:58
@ctrlplusb I'm commiting `lib` on master so you can install the plugin just running `npm i gcanti/babel-plugin-tcomb#master`, could you please give it a whirl? I'd love to hear if there are regressions with respect to v0.2

**Comment by zerkalica** [comment] 2016-06-10 10:38
@gcanti How do you plain to track situations with metadata, when flow definition placed in external library?

```js
// node_modules/myLib/flow-typed/interface.js
declare module 'myLib' {
  declare interface User {
    name: string;
  }
}
```

```js
// app.js
import type {User} from 'myLib'

function (user: User) {
// ...
}
```

**Comment by gcanti** [comment] 2016-06-10 13:20
@zerkalica currently fallbacks to `t.Any`:

```js
import type { User } from 'myLib'

function (user: User) {

}
```

compiles to

```js
var myLib = require('myLib');

function f(user) {
  _assert(user, typeof myLib.User !== "undefined" ? myLib.User : t.Any, 'user');

  console.log(user);
}
```

What do you suggest? (perhaps it's better to open a new issue though)

**Comment by ctrlplusb** [comment] 2016-06-12 17:13
@gcanti - installing this tomorrow. Shall report back with any issues. Pretty exciting stuff. I'm gonna experiment with the static checking too.

**Comment by gcanti** [comment] 2016-06-16 06:50
Hey @ctrlplusb how is going? The first impact with Flow can be overwhelming. I'd love to put up a babel-plugin-tcomb boilerplate showing what you can get in term of type safety, maybe with redux / react / etc.. Or perhaps even better, pick an existing boilerplate and add type annotations. Any ideas?

**Comment by volkanunsal** [comment] 2016-06-16 09:26
Not him, but I tried yesterday. There were some issues. The native flow
types weren't recognized and I had to create aliases for them. Maybe
because I didn't use the '@flow' comment at top of file? I will try again
today with flow enabled.

On Thursday, June 16, 2016, Giulio Canti <notifications@github.com> wrote:

> Hey @ctrlplusb <https://github.com/ctrlplusb> how is going? The first
> impact with Flow can be overwhelming. I'd love to put up a
> babel-plugin-tcomb boilerplate showing what you can get in term of type
> safety, maybe with redux / react / etc.. Or perhaps even better, pick an
> existing boilerplate and add type annotations. Any ideas?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gcanti/babel-plugin-tcomb/issues/11#issuecomment-226402315>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAJQMHSJq7DbSs0U6hOaNJ_Pd_gFdTRoks5qMPIzgaJpZM4H23ne>
> .
>


-- 
*Volkan Unsal*
*web and mobile development*
volkanunsal.com

**Comment by gcanti** [comment] 2016-06-16 10:53
Just pushed [babel-plugin-tcomb-boilerplate](https://github.com/gcanti/babel-plugin-tcomb-boilerplate), It's just the usual counter for now (I'll add other features step by step) but already shows the great benefits of having both static and runtime type checking. Feeding Flow is a little bit verbose but it's awesome having the whole app type checked.

**Comment by gcanti** [comment] 2016-06-16 11:20
@volkanunsal yesterday I fixed (https://github.com/gcanti/babel-plugin-tcomb/commit/73a21047d1d00cf9d0c6e0f2b1e81969e9386be7) a major problem with types imported from definition files (they were `undefined`).

> The native flow types weren't recognized

Feel free to open an issue with some excerpt of your code, so we can hopefully come up with a solution and/or enhance the test suite.

**Comment by gcanti** [comment] 2016-06-16 14:49
Elm architecture with Flow and babel-plugin-tcomb: https://github.com/gcanti/babel-plugin-tcomb-boilerplate/tree/elm/src

**Comment by minedeljkovic** [comment] 2016-06-16 19:44
> Elm architecture with Flow and babel-plugin-tcomb: https://github.com/gcanti/babel-plugin-tcomb-boilerplate/tree/elm/src

@gcanti This is funny, I was also playing for the last week or so with Elm architecture in Redux, statically type checked with flow. I just pushed it to github today:
https://github.com/minedeljkovic/redux-elmish

I'd love to hear someone's comment or suggestion on this.

I am also very interested to use this repo to produce tcomb types for runtime introspection. For now I think of decoding part of model with fromJSON and tagged actions pretty print in redux devtools (with the help of tcomb union).

**Comment by gcanti** [comment] 2016-06-16 20:14
@minedeljkovic Really interesting and a great resource, thanks for sharing
